version: '3.1'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: tree_hust
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3307:3306"
    networks:
      - internal_network
    expose:
      - 3306


  backend:
    build: 
      context: backend
    # image: tree_hust_api
    restart: always
    ports:
      - "8000:8000"
      - "25:25"
    networks:
      - internal_network
    depends_on:
      - db
    expose:
      - 8000
    # command: sh run.sh
    

  frontend:
    build: 
      context: website
    # image: tree_hust_frontend
    restart: always
    ports:
      - "3000:3000"
      - "8080:80"
      # - "443:443"
    networks:
      - internal_network
    depends_on:
      - backend
    expose:
      - 3000
      - 80

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./build:/usr/share/nginx/html  # need to be built first
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - internal_network
    depends_on:
      - backend
      - frontend
      - db


networks:
  internal_network: 
    driver: bridge

volumes:
  data:
    driver: local

